"""Initial migration, featuring admin flag

Revision ID: 185373d629f4
Revises: 
Create Date: 2020-05-01 13:43:43.956774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '185373d629f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'admin')
    # ### end Alembic commands ###
